 /******************************************************************************
 *
 * Module: ULTRASONIC
 *
 * File Name: ultrasonic.c
 *
 * Description: Source file for the AVR ULTRASONIC driver
 *
 * Author: Haidy Raouf
 *
 * Created on: Mar 4, 2022
 *
 *******************************************************************************/


#include "common_macros.h" /* To use the macros like SET_BIT */
#include "ultrasonic.h"
#include "gpio.h"
#include "icu.h"
#include <util/delay.h> /* For the delay functions */

uint8 g_edgeCount = 0;
uint16 g_timeHigh = 0;


/*******************************************************************************
 *                      Functions Definitions                                  *
 *******************************************************************************/
 /*
 * Description :
 * Initialize the ULTRASONIC:
 * 1.Initialize the ICU driver as required.
 * 2.Setup the ICU call back function.
 * 3.Setup the direction for the trigger pin as output pin through the GPIO driver.
 */
void Ultrasonic_init(void)
{
	/* Create configuration structure for ICU driver */
	Icu_ConfigType Icu_Config = {F_CPU_8,RISING};
	/* Set the Call back function pointer in the ICU driver */
	Icu_setCallBack(Ultrasonic_edgeProcessing);
	Icu_init(&Icu_Config);
	/* Configure the direction for the trigger pin as output pins */
	GPIO_setupPinDirection(ULTRASONIC_TRIGGER_PORT_ID,ULTRASONIC_TRIGGER_PIN_ID,PIN_OUTPUT);
}

/*
* Description :
*Send the Trigger pulse to the ultrasonic.
*/
void Ultrasonic_Trigger(void)
{
	GPIO_writePin(ULTRASONIC_TRIGGER_PORT_ID, ULTRASONIC_TRIGGER_PIN_ID, LOGIC_HIGH);
	_delay_us(10);
	GPIO_writePin(ULTRASONIC_TRIGGER_PORT_ID, ULTRASONIC_TRIGGER_PIN_ID, LOGIC_LOW);

}

/*
* Description :
* 1.Send the trigger pulse by using Ultrasonic_Trigger function.
* 2.Start the measurements by the ICU from this moment.
*/
uint16 Ultrasonic_readDistance(void)
{
	uint16 distance=0;
	Ultrasonic_Trigger();
	distance=g_timeHigh/58.8;
	return distance;

}

/*
* Description :
* 1. This is the call back function called by the ICU driver.
* 2.This is used to calculate the high time (pulse time) generated by the ultrasonic sensor
*/
void Ultrasonic_edgeProcessing(void)
{
	g_edgeCount++;
	if(g_edgeCount == 1)
		{
	          /*
			 * Clear the timer counter register to start measurements from the
			 * first detected rising edge
			 */
			Icu_clearTimerValue();
			/* Detect falling edge */
			Icu_setEdgeDetectionType(FALLING);
		}
	else if (g_edgeCount==2)
	{
		/* Store the High time value */
		g_timeHigh = Icu_getInputCaptureValue();
		Icu_setEdgeDetectionType(RISING);
	}

}
